README.md
link to docs was broken
fixes readme link to docs
make readme consitent
=> docs: Update docs link

scripts/localnet.sh
Whitelist both eth and btc in our localnet
Local testing of oracle and py-sdk
=> feat: whitelist ubtc and ueth in pricefeed

CHANGELOG.md, x/perp/handler.go
Allow users to send multiliquidate txs
improve liquidator reliability
=> feat: wire multi-liquidate into the grpc

CHANGELOG.md, x/dex/keeper/keeper.go, x/dex/keeper/swap_test.go, x/dex/types/errors.go, x/dex/types/pool.go, x/dex/types/pool_test.go, x/dex/types/shares.go
We have a bug in testnet where some particular pool configuration for stable swap are causing a panic and stopping the chain.
Restart testnet
=> fix: unexpected panic in stableswap calcs

CHANGELOG.md, scripts/localnet.sh
We don't have prices on localnet, which is annoying
Ease up quick local testing
=> fix: publish prices at genesis for localnet

CHANGELOG.md, x/oracle/keeper/ballot.go, x/oracle/keeper/ballot_test.go, x/oracle/keeper/reward.go, x/oracle/keeper/tally.go, x/oracle/keeper/tally_fuzz_test.go, x/oracle/keeper/update_exchange_rates.go, x/oracle/keeper/update_exchange_rates_test.go, x/oracle/types/ballot.go, x/oracle/types/vote.go
- replaces the validator performance map with a type alias
- use set.Set[asset.Pair] for whitelist map
Readability
=> refactor(oracle): types

CHANGELOG.md
Updates the changelog for the `v0.19.2` release
Clean changelogs for developers.
=> chore: update changelog for v0.19.2 release

CHANGELOG.md, x/perp/amm/keeper/pool_state.go
Closes: https://github.com/NibiruChain/nibiru/issues/1265
=> feat: SqrtDepth equal to base reserves when pool creation 

.github/workflows/e2e-wasm.yml, contrib/scripts/localnet.sh
Adds peg-multiplier when creating perp vpools.
Fixes local testing
=> fix: localnet script

INSTALL.md, README.md
=> docs: fix typos

CHANGELOG.md, x/perp/keeper/v2/swap.go, x/perp/keeper/v2/swap_test.go, x/perp/types/v2/amm.go
- SwapQuoteAsset
- SwapBaseAsset
- tests
#1310
=> feat: add PerpKeeperV2 swap methods

CHANGELOG.md, app/keepers.go, x/perp/keeper/v2/hooks.go, x/perp/keeper/v2/hooks_test.go
- adds `AfterEpochEnd` hook for updating market funding rates
- wires hooks into `app.EpochsKeeper`
#1310
=> feat(perp): add hooks for updating funding rate

CHANGELOG.md, x/perp/integration/action/v2/params.go, x/perp/integration/action/v2/position.go, x/perp/keeper/v2/clearing_house.go, x/perp/keeper/v2/clearing_house_test.go, x/perp/keeper/v2/keeper.go, x/perp/types/v2/errors.go
=> feat(perp): market not enabled can only be used to close out existing positions

CHANGELOG.md, x/perp/integration/action/v2/liquidation.go, x/perp/keeper/v2/liquidate.go, x/perp/keeper/v2/liquidate_test.go, x/perp/keeper/v2/withdraw.go
- add `MultiLiquidate` method on PerpKeeperV2
- add integration tests
#1310
=> feat(perp): add liquidate method

.gitignore, contrib/make/build.mk
=> ci: fetch librocksdb for local build

contrib/make/build.mk, contrib/scripts/localnet.sh
=> fix(build): fix missing rocksdb flag

CHANGELOG.md, x/perp/v2/integration/action/market.go, x/perp/v2/keeper/admin.go, x/perp/v2/keeper/admin_test.go, x/perp/v2/module/abci.go, x/perp/v2/module/abci_test.go
- add `CreatePool` keeper method to `perpv2`
- add ABCI hook to store `ReserveSnapshots`
#1310
=> feat(perp): CreatePool keeper method

.github/workflows/docker-chaosnet.yml, .goreleaser.yml, Dockerfile, contrib/make/release.mk
=> feat(ci): build docker image on goreleaser

.goreleaser.yml, contrib/docker/chaosnet.Dockerfile, contrib/make/build.mk, contrib/scripts/chaosnet.sh
=> feat(make): link wasmvm statically and fix chaosnet

.github/workflows/docker-publish.yml, .github/workflows/goreleaser.yml, .goreleaser.yml, Dockerfile, contrib/docker/chaosnet.Dockerfile, contrib/docker/goreleaser.Dockerfile, contrib/make/build.mk, contrib/make/release.mk
- update chaosnet docker workflow
- simplify nibiru docker image creation
- have goreleaser create canonical binaries
- fix make commands for amd64
Automates our binary creation process
=> ci: fix docker and goreleaser

.github/workflows/proto-lint.yml, proto/buf.gen.ts.yaml
Creates a buf config file for generating ts protos
Used by the protojs package.
=> ci(proto): create ts protogen buf config file

CHANGELOG.md, cmd/nibid/cmd/root.go, contrib/scripts/localnet.sh, x/sudo/cli/cli_test.go, x/sudo/cli/gen_root.go, x/sudo/cli/gen_root_test.go, x/sudo/types/genesis.go, x/sudo/types/msgs.go
=> feat: create cli to add sudo account into genesis

CHAOSNET.md, contrib/docker-compose/docker-compose-chaosnet.yml, contrib/make/chaosnet.mk, contrib/scripts/chaosnet.sh, contrib/scripts/localnet.sh
- Fixes chaosnet (chain + pricefeeder + heartmonitor + faucet) for local testing
Enables local testing
=> ci(chaosnet): fix chaosnet for v0.21

.github/workflows/coverage.yml, CHANGELOG.md, codecov.yml, go.mod, x/epochs/abci.go, x/epochs/abci_test.go, x/epochs/genesis.go, x/epochs/genesis_test.go, x/epochs/integration/action/epoch.go, x/epochs/keeper/epoch.go, x/epochs/keeper/grpc_query.go, x/epochs/keeper/grpc_query_test.go, x/epochs/keeper/hooks_test.go, x/epochs/keeper/keeper.go, x/epochs/keeper/keeper_test.go, x/epochs/module.go, x/epochs/types/epochinfo.go, x/epochs/types/epochinfo_test.go, x/epochs/types/genesis_test.go, x/epochs/types/hooks_test.go, x/perp/v2/keeper/hooks.go, x/perp/v2/types/expected_keepers.go
=> test: increase test coverage for x/hooks

x/perp/v2/types/msgs.go, x/spot/types/message.go, x/stablecoin/types/messages.go, x/sudo/types/msgs.go
Ensures each module's msgs conform to the `sdk.Tx` interface.
Also ensures `x/sudo`'s msgs conform to the `legacytx.LegacyMsg` interface since it's used with amino multisig.
Closes #1603
=> chore: msg interfaces

CHANGELOG.md, app/app.go
Needed to properly export the wasm bytecode for snapshots
=> feat(app)!: wasm snapshot export is mandatory

contrib/make/test.mk
=> fix: ci not showing errors

CHANGELOG.md, go.mod, go.sum
=> feat: update wasmd to v0.44.0

CHANGELOG.md, proto/buf.gen.ts.yaml
=> refactor: Update parameters

CHANGELOG.md, proto/buf.gen.ts.yaml
Main variant of https://github.com/NibiruChain/nibiru/pull/1770
=> refactor: buf-gen

CHANGELOG.md, app/evmante_sigverify_test.go, app/evmante_validate_basic_test.go, gosdk/keys.go, gosdk/keys_test.go
- fix: go-sdk add signer fix for kring
- refactor: removing unused go-sdk keyring funcs
- Closes #1897
=> fix(gosdk): fix keyring import functions

CHANGELOG.md, x/evm/precompile/funtoken.go
=> chore(evm): Set appropriate gas value for the required gas of the "IFunToken.sol" precompile.

CHANGELOG.md, app/evmante/evmante_gas_consume.go, x/evm/precompile/oracle.go
- Closes https://github.com/code-423n4/2024-10-nibiru-zenith/issues/38
=> refactor(evm): remove outdated comment and improper error message text

CHANGELOG.md, cmd/nibid/cmd/genaccounts.go, eth/rpc/backend/backend_suite_test.go, x/evm/keeper/bank_extension.go, x/evm/keeper/msg_server.go
- This change fixes https://github.com/zenith-security/2025-01-nibiru-mr-zenith/issues/7
=> fix(cmd): Continue from #2127 and unwire vesting flags and logic from genaccounts.go

CHANGELOG.md, x/evm/keeper/bank_extension.go
- Closes https://github.com/zenith-security/2025-01-nibiru-mr-zenith/issues/2
=> fix(evm): bank keeper extension gas meter type

.github/workflows/chaosnet-docker.yml, CHANGELOG.md
=> ci(chaosnet): fix docker image build

CHANGELOG.md, go.mod, go.sum
=> chore(wasm): bump wasmvm dependency to wasmvm v1.5.8

CHANGELOG.md, app/app.go, app/app_config.go, app/keepers.go, app/keepers/all_keepers.go, x/evm/evmmodule/module.go
=> feat: add depinject wiring for bank

CHANGELOG.md, app/export.go, app/simapp/sim_test.go
=> fix: simulation tests by register interfaces for vesting and use correct app keys field

CHANGELOG.md, app/app.go, app/app_config.go, app/keepers.go, app/keepers/all_keepers.go
=> feat: add depinject wiring for all sdk modules

CHANGELOG.md, app/app.go, app/keepers.go
- remove transient and memkeys from app
- refactor privateKeepers
=> refactor(app): remove unnecessary app fields

x/common/testutil/testnetwork/validator_node.go
remove duplicate package imports
=> refactor(go.mod): remove duplicate package imports

CHANGELOG.md, cmd/nibid/cmd/root.go
=> fix: use tmp directory for pre-instantiating app

.github/workflows/release.yml, CHANGELOG.md
=> ci(release): pack nibid binary with no enclosing directory

.github/workflows/release.yml, CHANGELOG.md
=> chore(ci): use shell script for generating changelog in releases

CHANGELOG.md, evm-e2e/test/wrapped_nibiru_wnibi.test.ts
=> test(evm-e2e): WNIBI tests for deposit, transfer and total supply
