- CHANGELOG.md
- cmd/nibid/cmd/init.go
- cmd/nibid/cmd/root.go
Overwrites the Tendermint consensus params related to block time in `nibid init`. 
- Closes #1053
Reference: [cosmos-sdk/x/genutil/client/cli/init.go](https://github.com/cosmos/cosmos-sdk/blob/v0.45.10/x/genutil/client/cli/init.go)
> feat: hard-code consensus params

- x/perp/keeper/clearing_house_integration_test.go
- x/perp/keeper/clearing_house_unit_test.go
Adds a `PositionChangedEvent` check to the `OpenPosition` success test cases. The `decreasePosition` and `increasePosition` keeper functions don't send the `PositionChangedEvent` due to not calling `afterPositionUpdate`, so the event check cannot be in the unit tests.
Verifies that we're sending the correct values in the `PositionChangedEvent`.
> test: add additional PositionChangedEvent test

- CHANGELOG.md
- x/pricefeed/client/cli/cli_test.go
- x/testutil/cli/gov.go
- x/vpool/client/cli/cli_test.go
Improves readability of the governance proposal CLI tests using `testutilcli.PassGovProposal`
> refactor(testutil): Less repetition. Move PassGovProposal to x/testutil

- scripts/protocgen.sh
This should fix the `make proto-gen` and its effects on the dependencies.
> fix: pin cosmos-sdk version to v0.45.10

- CHANGELOG.md
- x/dex/types/pool.go
Join pool for unsorted token generate a panic and it should not be up to the user to sort them in the transaction.
found in py-sdk with:
```python
nibiru.msg.MsgJoinPool(
sender=agent.address,
pool_id=pool_ids["uusdc:unusd"],
tokens=[Coin(100, "uusdc"), Coin(100, "unusd")],
),
```
QoL
> fix: sort tokens in join pool to avoid panic

- CHANGELOG.md
- x/dex/keeper/keeper.go
- x/dex/keeper/keeper_test.go
- closes #1112 
Single asset join is blocked unless the user provide `--tokenIn 0unibi,100unusd`
> fix(dex): fix single asset join

- scripts/localnet.sh
Sets the vote period to 10 blocks on localnet.
It's impossible to test price-feeder locally if the vote period is set too high.
> fix: set vote period to 10 blocks

- CHANGELOG.md
- x/oracle/genesis.go
- x/oracle/genesis_test.go
- x/oracle/keeper/ballot.go
- x/oracle/keeper/ballot_test.go
- x/oracle/keeper/keeper.go
- x/oracle/keeper/querier_test.go
- x/oracle/keeper/reward.go
- x/oracle/keeper/reward_test.go
- x/oracle/keeper/slash_test.go
- x/oracle/keeper/tally.go
- x/oracle/keeper/tally_fuzz_test.go
- x/oracle/keeper/test_utils.go
- x/oracle/keeper/update_exchange_rates.go
- x/oracle/keeper/update_exchange_rates_test.go
- x/oracle/keeper/vote_target.go
- x/oracle/keeper/vote_target_test.go
- x/oracle/types/ballot.go
- x/oracle/types/ballot_test.go
Renames functions and variables for clarity.
Does not introduce any business logic changes.
> refactor(oracle): rename functions and variables for readability

- .github/workflows/docker-publish.yml
Fixes bug from this workflow run: https://github.com/NibiruChain/nibiru/actions/runs/4007449459/workflow
> ci(docker-publish.yml): fixes yaml syntax error

- CHANGELOG.md
- contrib/make/chaosnet.mk
- contrib/scripts/chaosnet.sh
- contrib/scripts/localnet.sh
Sets the `min_voters` locally to 1, for testing purposes.
Local testing is broken because the oracle enforces at least 4 voters for pairs.
> fix(oracle): local min voters

- .github/workflows/proto-gen.yml
- .github/workflows/skip-proto-gen.yml
- CHANGELOG.md
- contrib/scripts/protocgen.sh
This PR adds a workflow to verify that `make proto-gen`  works whenever the `.proto` files change or the proto generation scripts change.
> ci: create workflow to test make proto-gen when the script or .proto files change

- .github/workflows/coverage.yml
- .github/workflows/skip-coverage.yml
- CHANGELOG.md
- contrib/scripts/localnet.sh
Right now, the Coingecko API request is returning an error code 1020 for "access denied". Since the request technically succeeds but doesn't return the necessary prices in JSON format, the `localnet.sh` halts when dividing numbers to compute the price. 
This PR adds a condition to return out of the Coingecko function in the script if there aren't prices, which makes it default to hard-coded values for the price of BTC and ETH.
I noticed that a 7 minute workflow ran for Go tests after adding the `localnet.sh` change. For consistency with the unit and integration test workflows, this PR also adds a path-based condition to the `coverage.yml` workflow so that it only runs when .go or .proto files change.
> fix(localnet.sh): force localnet.sh to work even if coingecko is down

- CHANGELOG.md
- x/perp/keeper/v2/calc.go
- x/perp/keeper/v2/calc_test.go
- x/perp/keeper/v2/clearing_house.go
- `checkOpenPositionRequirements` checks that the quote asset amount and leverage parameters are okay
- `transferFee` sends fees to the exchange fee pool and ecosystem fund
- `checkPriceFluctuationLimitRatio` checks if the change in mark price is greater than allowed
Tests will follow with #1303.
It makes adding the clearing house `OpenPosition` and `ClosePosition` functions easier.
See #1310 for more details.
> feat(perp): add basic clearing house methods

- contrib/make/build.mk
- contrib/scripts/localnet.sh
Setting up rocksdb locally requires some extra linking, so we'll revert to local leveldb for now and use rocksdb in our production nodes
> fix: revert to goleveldb for localnet

- CHANGELOG.md
- x/oracle/keeper/hooks.go
- x/oracle/keeper/hooks_test.go
Diverts rewards from the perpv2 module instead of perpv1 module.
#1310
> refactor(oracle): send rewards from perpv2 instead of perpv1

- x/perp/v2/client/cli/cli_test.go
- x/perp/v2/types/keys.go
For some reason, the perpv2 module name key cannot start with `perp`, or else the `perpv1` genesis state gets passed into `perpv2`'s `InitGenesis`.
#1310
> fix: make localnet

- contrib/make/build.mk
- Use the `uname -m` for determining computer arch instead of `uname -p`, which does not resolve to `x86_64` ever.
x86_64 machines were not able to build locally because it kept downloading the wrong librocksdb library.
> fix: fix build makefile

- CHANGELOG.md
- x/oracle/keeper/hooks.go
- x/oracle/keeper/hooks_test.go
- handles the case where oracle rewards are truncated to zeor
- removes panics from oracle's AfterEpoch hook
#1375
> fix(oracle): handle zero oracle rewards

- CHANGELOG.md
- cmd/nibid/cmd/init.go
- cmd/nibid/cmd/root.go
https://github.com/NibiruChain/nibiru/assets/51418232/1153a7b7-8cdb-4ed4-8922-e4435ae8266c
---
> "...realized that with the new v47 upgrade ...we're seeing 5 second block times. Was there an update to the config anywhere?"
> fix(root.go): add custom InitCmd that sets the desired Tendermint consensus parameters

- contrib/scripts/localnet.sh
- adds `sudo` genesis state with validator address as `root`
- updates broadcast-mode to `sync` since `block` no longer exists in Cosmos SDK v47
- use gorocksdb backend
- fixes localnet
> fix(localnet): add sudo state and fix config

- CHANGELOG.md
- x/inflation/keeper/hooks.go
- x/oracle/keeper/reward.go
- x/oracle/keeper/slash.go
- continue with processing the oracle abci hook even in the presence of partial errors
Auditors found an issue where objects could be nil because we continue with the code flow even in the presence of partial errors.
> fix(oracle): continue with abci hook during error

- proto/buf.gen.ts.yaml
- adds the connect-es plugin to the Buf config
`connect-es` generates TypeScript gRPC code, which was missing from just the `es` plugin
> feat: add connect-es plugin

- proto/buf.gen.ts.yaml
- revert to ts-proto plugin
ts-proto is the only TypeScript proto-gen plugin that is compatible with CosmJS.
> fix(proto): update ts proto gen config

- CHANGELOG.md
- cmd/nibid/cmd/root.go
- contrib/scripts/localnet.sh
- x/oracle/client/cli/gen_pricefeeder_delegation.go
- x/oracle/client/cli/gen_pricefeeder_delegation_test.go
- creates a genesis cmd `add-genesis-pricefeeder-delegation` which allows adding pricefeeder delegations to the genesis state
- moves the `add-genesis-perp-market` cmd under the `genesis` sub-command
It makes setting up a devnet/testnet much easier.
> feat(oracle): add genesis cmd to create pricefeeder delegation

- CHANGELOG.md
- app/keepers.go
- wire legacy proposal handlers to the `gov` keeper
- initialize param key tables so that legacy gov proposals can modify params
Without this PR, legacy governance proposals cannot update module params.
The below is an example of what happens when trying to change the `MaxValidators` param of the `x/staking` module on the current nibid version (localnet).
```json
{
"height": "4",
"txhash": "45E00592BBAB2840F271D9A6AF1EB57C816F76C2C84F59405DF7AC90C5040E66",
"codespace": "undefined",
"code": 111222,
"data": "",
"raw_log": "recovered: runtime error: invalid memory address or nil pointer dereference\nstack:\ngoroutine 30 [running]:\nruntime/debug.Stack()\n\t/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/debug/stack.go:24 +0x64\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddlew …
```
> fix(gov): legacy proposals were not wired

- CHANGELOG.md
- x/wasm/binding/exec.go
- x/wasm/binding/exec_perp.go
- x/wasm/binding/exec_perp_test.go
- x/wasm/binding/exec_test.go
- x/wasm/binding/querier_perp_test.go
- x/wasm/binding/querier_test.go
> fix(wasm)!: call `ValidateBasic` before all `sdk.Msg` calls for the bindings-perp contract + remove sudo permissioning

- go.mod
- x/oracle/simulation/decoder.go
- x/oracle/simulation/decoder_test.go
- x/perp/v2/integration/assertion/event.go
- x/spot/keeper/grpc_query.go
- x/spot/keeper/keeper.go
- x/stablecoin/client/cli/cli_test.go
- x/sudo/cli/cli_test.go
This PR fixes the event field assertion logic in tests. 
We were using the `gogo/protobuf` type registry for checking `MessageName()`, which always returned an empty string since the `gogo/protobuf` module is no longer used in the SDK. That meant that https://github.com/NibiruChain/nibiru/blob/master/x/perp/v2/integration/assertion/event.go#L157 never succeeded and we were skipping event field assertions.
After fixing the check, I noticed that certain event fields weren't in the proper format (e.g. `badDebt` and `transactionFee` came in JSON format from `EventAttributes`, but we were wanting the `String()` representation), so I fixed those fields too.
There's also some code cleanup in this PR. I thought about why we needed an interface for the `eventEquals` struct but couldn't think of …
> fix(perp): event field assertion tests

- x/common/testutil/events.go
- x/perp/v2/integration/assertion/event.go
- x/perp/v2/keeper/liquidate_test.go
This PR refactors the event comparison logic to use `reflect.DeepEqual` instead of rolling our own comparison logic. `reflect.DeepEqual` is more robust at handling proto structs and automatically picks up new proto fields by introspecting the type at runtime (test time).
Without it, we won't be able to properly assert events.
> fix(test): position changed event comparison

- contrib/scripts/localnet.sh
- uses the correct sudo genesis cmd
- modifies oracle params to be useable with only one pricefeeder
Makes local development easier
> fix: update localnet script

- app/app.go
- app/keepers.go
- app/modules.go
- Removes unused code in app setup
- Clean up import list
- General style fixes
Makes app setup easier to read
> refactor(app): remove dead code in app setup

- .goreleaser.yml
- CHANGELOG.md
> chore(goreleaser): update wasmvm to v1.4.0

- .github/workflows/changelog-deps.yml
- .github/workflows/coverage.yml
- .github/workflows/docker-publish.yml
- .github/workflows/e2e-wasm.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/goreleaser.yml
- .github/workflows/integration-tests.yml
- .github/workflows/proto-lint.yml
- .github/workflows/sims.yml
- .github/workflows/unit-tests.yml
Reverts the gha checkout action to v3
Reverts the gha codecov action to v3
Checkout v4 is causing our golangci-lint workflow to [fail](https://github.com/NibiruChain/nibiru/actions/runs/6211228223/job/16868063322?pr=1586).
Codecov v4 is causing our workflows to fail.
> revert(gha): use checkout and codecov action v3

- .github/workflows/integration-tests.yml
- contrib/make/test.mk
- x/perp/v2/keeper/clearing_house.go
The codecov reports stopped being published and used to work in prior commits like https://github.com/NibiruChain/nibiru/commit/d0bc88444037e6a6ab4b21bd28081d0ee6f1f284 and tag v0.21.8. 
This PR is intended to restore the functionality for publishing coverage reports (I think it's simply removing a flag).
> ci: fix coverage report publishing

- CHANGELOG.md
- app/app.go
This change affects keeper tests but does not affect the initialization of actual binaries (cmd/.../root.go).
- This more closely resembles the [logic in wasmd](https://github.com/CosmWasm/wasmd/blob/03f3c72a6ce447fafc2da023a1322899327433f8/app/app.go#L769-L779)
- hotfix(app): non-nil snapshot manager is not guaranteed in testapp
> fix(app): non-nil snapshot manager is not guarantted in testapp

- CHANGELOG.md
- wasmbinding/exec_oracle_test.go
- x/oracle/abci_test.go
- x/oracle/keeper/msg_server_test.go
- x/oracle/keeper/reward_test.go
- x/oracle/keeper/slash_test.go
- x/oracle/keeper/update_exchange_rates_test.go
- x/oracle/types/params.go
Curates the default genesis whitelist of oracle pairs for mainnet.
Since we won't have NUSD at genesis time, we don't need the oracle prices paired against NUSD.
Since we don't have NIBI prices on external exchanges at genesis time, we can remove it and add it later.
Smooth mainnet launch
> chore(oracle): curate default oracle whitelist

- contrib/docker/chaosnet.Dockerfile
Remotes the `/nibiru/temp` cache directory. 
Caching the `temp` directory causes the wrong version of the library to used, which is especially bad when we do multi-platform builds. For example, [this run](https://github.com/NibiruChain/nibiru/actions/runs/7251871181/job/19755132894) was broken because an incompatible libwasmvm was cached.
> ci: remove temp directory caching which causes stale libs

- .github/workflows/e2e-wasm.yml
- CHANGELOG.md
- contrib/make/localnet.mk
- contrib/scripts/chaosnet.sh
- contrib/scripts/e2e/deploy-wasm.sh
- contrib/scripts/feat-perp.sh
- contrib/scripts/localnet.sh
- justfile
- x/devgas/v1/keeper/keeper.go
- x/epochs/keeper/hooks_test.go
- x/epochs/types/hooks.go
- x/inflation/doc.go
- x/inflation/keeper/grpc_query.go
- x/inflation/keeper/hooks.go
- x/inflation/keeper/hooks_test.go
- x/inflation/keeper/inflation.go
- x/inflation/keeper/keeper.go
- x/inflation/keeper/msg_server.go
- x/inflation/keeper/sudo.go
- x/inflation/types/inflation_calculation_test.go
Originally, I opened this to add some doc comments and delete unused code. When I opened the PR, I noticed that the localnet.sh was not running on the branch and was also broken on `main`. I've gone ahead and fixed that.
In addition, both `just localnet` and `make localnet` now use feature flags to enable modules like x/perp and x/spot, which will make tests a lot less finicky. 
- Fixed scripts/chaosnet.sh
- Fixed scripts/localnet.sh
- Documented x/inflation more thoroughly in each file.
- Slight no-op refactor in x/inflation to delete unused code
- **New Features**
- Added functions to configure initial reserve values for genesis perpetual markets and query market prices.
- **Enhancements**
- Enhanced localnet script with bash, flag parsing for build options, and feature flags for `perp` …
> fix(inflation-docs): 1 Document inflation, 2 delete unused code, 3 fix CI

- CHANGELOG.md
- app/keepers.go
Add ICA controller stack to Nibiru Chain. See https://github.com/CosmWasm/wasmd/blob/main/app/app.go#L655-L669 for a reference implementation.
Relates to #1820.
> fix(ica): add controller stack

- app/keepers.go
- eth/chain_id.go
- x/common/error.go
- x/evm/cli/cli.go
- x/evm/codec.go
- x/evm/const.go
- x/evm/deps.go
- x/evm/evmmodule/genesis.go
- x/evm/evmmodule/module.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/hooks.go
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/keeper/msg_server.go
- Part of #1836
- This PR wires the EVM Module into the `BaseApp`, using placeholder functions to satisfy the `AppModule` interface methods.
> feat(evm): module and keeper start

- CHANGELOG.md
- app/evmante/evmante_validate_basic_test.go
- x/evm/evmmodule/genesis.go
- x/evm/keeper/evm_state.go
- x/evm/keeper/grpc_query_test.go
- x/evm/keeper/msg_update_params.go
- closes https://github.com/code-423n4/2024-10-nibiru-zenith/issues/33
> feat(evm): add simple validation for fun token fee in set params

- CHANGELOG.md
- x/evm/keeper/bank_extension.go
- Addresses https://github.com/code-423n4/2024-11-nibiru-findings/issues/26
> fix(bank): add additional missing bank keeper method overrides to sync with StateDB

- CHANGELOG.md
- evm-e2e/contracts/NibiruOracleChainLinkLike.sol
- evm-e2e/test/nibiru_oracle.test.ts
- evm-e2e/test/utils.ts
- justfile
- Closes #2075  
Completes this part in particular
> - [ ] Add the ChainLink-like oracle deployment and query to the EVM E2E test suite
> test(evm-e2e): add E2E test using the Nibiru Oracle's ChainLink impl

- CHANGELOG.md
- x/evm/precompile/funtoken.go
- Fixes https://github.com/NibiruChain/nibiru/issues/2158
The 3 methods where the above ticket might potentially play a role are `sendToBank`, `sendToEvm` and `bankMsgSend`. 
- `sendToBank`  does not need any changes because it uses "SendCoinsFromModuleToAccount" to send Bank Coins, and this method correctly avoids sending funds to addresses blocked by the Bank module.
- Similarly, `sendToEvm` does not need changes because the only bank.MsgSend operation involved is when the signer transfers funds to the EVM module 
- `bankMsgSend` does include a change because `BaseSendKeeper.Send` does not have the blocked address check, so I've switched that to use `bank.MsgServer.Send`, as it's safer and includes the blocking behavior.
> fix(evm-precompile): use bank.MsgServer Send in precompile IFunToken.bankMsgSend

- CHANGELOG.md
- x/evm/embeds/artifacts/contracts/MKR.sol/DSAuth.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSAuthEvents.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSAuthority.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSMath.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSNote.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSStop.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSThing.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSToken.json
- x/evm/embeds/artifacts/contracts/MKR.sol/DSTokenBase.json
- x/evm/embeds/artifacts/contracts/MKR.sol/ERC20.json
- x/evm/embeds/contracts/MKR.sol
- x/evm/embeds/embeds.go
- x/evm/embeds/embeds_test.go
- x/evm/embeds/hardhat.config.js
- x/evm/keeper/erc20.go
- x/evm/keeper/funtoken_from_coin_test.go
- x/evm/keeper/funtoken_from_erc20.go
- x/evm/keeper/funtoken_from_erc20_test.go
This pull request includes several changes to the way evm keeper find erc20 metadata , focusing on handling trying to unpack returned data from evm function in `LoadERC20String` and `loadERC20Uint8`. For example, MKR have  `name`, `decimals`, and `symbol` encoded differently from erc20 token standart. 
- Add `TestFindMKRMetadata` function to deploy MKR token and find its metadata
- Add MKR embeds as `SmartContract_TestBytes32Metadata` in embeds.go
- Add MKR artifacts
- Add a new function parameter for `FindERC20Metadata` which is an optional abi. It will use this optional abi or else use the default one which is `SmartContract_ERC20Minter`
- Add `ERC20Bytes32` for unpacking bytes32 in solidity
> fix(evm): Better handling erc20 metadata

- CHANGELOG.md
- x/epochs/keeper/epoch.go
Based on [L-01 | Unclosed Iterator in IterateEpochInfo](https://github.com/code-423n4/2024-11-nibiru-findings/blob/main/data/gumgumzum-Q.md#l-01--unclosed-iterator-in-iterateepochinfo)
> chore: close iterator in IterateEpochInfo

- CHANGELOG.md
- eth/eip55.go
- eth/eip55_test.go
- Closes #2185 
At some point between RC14 and RC19, EIP55 address encoding changed and broke state reads. This PR fixes the proto and JSON marshaling functions.
I tested the PR by first spinning up a localnet with RC14, creating and converting some funtokens, then hot swapping to the binary on this branch. Funtoken conversions continued to succeed, whereas with RC19 they would've failed. 
Note: it may break downstream ts-sdk clients, which will unfortunately have to be fixed in TypeScript. Looking at https://github.com/cosmos/gogoproto/blob/v1.5.0/custom_types.md, we follow Alternative 2) which "makes it harder to generate protobuf code in other languages". We are simply experiencing the downstream effects of decisions we made for our protobufs earlier on. 
Related PRs:
- #2120
- #2154
> fix(evm)!: correct EIP55 addr encoding

- CHANGELOG.md
- x/evm/evmtest/erc20.go
- x/evm/keeper/call_contract.go
- x/evm/keeper/funtoken_from_coin.go
- x/evm/keeper/funtoken_from_coin_test.go
- x/evm/keeper/funtoken_from_erc20_test.go
- x/evm/keeper/msg_server.go
- x/evm/precompile/funtoken.go
- funtoken precompile `sendToBank` call duplicated logs due to outdated code
- ConvertCoinToEvm for erc20 born coins did not emit Transfer tx log
- CreateFunToken from coin did not emit log of contract creation
> fix(evm): proper eth tx logs emission for funtoken operations

- evm-forge/README.md
Hi! I fixed a broken link to the Solidity Scripting tutorial. The updated link now points to the correct guide.
> fix: update 404 link README.md

- CHANGELOG.md
- app/evmante/evmante_sigverify.go
- app/evmante/evmante_sigverify_test.go
A lot of integration partners have been trying to deploy multicall contracts which fail due to the tx not containing the EIP155 chain id in the signature.
We rely on the backend JSON-RPC config for nodes to disable allowing non-replay protected txs.
> fix(evm): disable unprotected tx check in EVM ante handler

- evm-core-ts/src/ethers/index.ts
I’ve corrected a typo where the word "inteface" was used instead of "interface".
> chore: fix typo in the code

- CHANGELOG.md
- eth/rpc/backend/blocks.go
Block bloom is used in logs filtering. On mainnet it's missing for pre-evm blocks and causing error:
```
{
code: -32000,
message: 'eth.evm.v1.EventBlockBloom not found in end block results'
}
```
Returning empty block bloom for such blocks will produce empty tx logs which is an expected result.
> fix(evm): suppressing error on missing block bloom event

- CHANGELOG.md
- x/evm/precompile/funtoken.go
In `sendToEvm`, the `to` parameter accepts either an EVM address or a nibi address. In `sendToBank`, however, it only accepted a nibi address. To maintain parity and make it easier for developers calling `sendToBank` from an EVM contract, this PR updates the `sendToBank`'s `to` parameter to accept either an EVM or nibi address.
Long story short, it's a pain in the ass to convert from an EVM address to a bech32 address in Solidity (e.g. if you have a `msg.sender` and want to figure out the `nibi` representation).
> feat(funtoken): accept either a Nibiru address or EVM address in sendToBank

- CHANGELOG.md
- x/evm/keeper/erc20.go
- Changing the contract to ERC20MinterWithMetadata in #2251 increased the gas cost to deploy a contract beyond 2M gas units. Increasing the gas limit to 2.5M seems to work.
> fix(evm): update ERC20 deploy contract gas limit

- LEGACY-CHANGELOG.md
- x/evm/embeds/HACKING.md
hey team! I found duplicate words and fixed them.
> docs: remove consecutive duplicate words

- CHANGELOG.md
- x/evm/errors.go
According to [Solidity docs](https://docs.soliditylang.org/en/latest/control-structures.html#revert), contracts can revert with standard `revert(string)` or `revert CustomError()`.
In the former case, we end up with a message `execution reverted with reason "foo"` which is valid. But in the latter case, we try to blindly decode the bytes as UTF-8 which gives us invalid character sequences like `execution reverted, but unable to parse reason \"\t\ufffd\ufffd\ufffd\"`. 
This PR addresses the latter case and gives back the raw hex of the revert reason (which is the 4-byte ABI-encoding of the CustomError signature).
"Using a custom error instance will usually be much cheaper than a string description, because you can use the name of the error to describe it, which is encoded in only four …
> fix(evm): update revert error reason

- .github/workflows/changelog-check.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/integration-tests.yml
- .github/workflows/unit-tests.yml
- CHANGELOG.md
Glob patterns are not working as expected with the `nibiru-go` path filter used in our GitHub action tests.
I noticed this from one of our coverage reports missing on main. This PR fixes
that bug.
> fix(.github): glob patterns broken in nibiru-go filter for dorny/paths-filter

- CHANGELOG.md
- app/appconst/appconst.go
- eth/rpc/rpcapi/api_eth.go
- eth/rpc/rpcapi/api_eth_test.go
- eth/rpc/rpcapi/api_net_test.go
- eth/rpc/rpcapi/blocks_test.go
- eth/rpc/rpcapi/call_tx_test.go
- eth/rpc/rpcapi/tracing_test.go
- go.mod
- go.sum
- gosdk/README.md
- gosdk/gosdk_test.go
- gosdk/netinfo.go
- x/common/testutil/testnetwork/start_node.go
- x/common/testutil/testnetwork/validator_node.go
- Partially closes https://github.com/NibiruChain/nibiru/issues/2286
- This commit introduces a broad set of improvements and refactors across
the Nibiru EVM RPC interface
- Unified EVM RPC usage by replacing ad hoc `EthAPI` calls with a more
direct `EvmRpcClient` approach using typed JSON-RPC methods.
- Replaced deprecated or redundant `EthAPI` test calls (e.g.,
`SendRawTransaction`, `GetPendingTransactions`) with explicit
`ethclient` or raw RPC usage to improve reliability and alignment with
production.
- Enhanced EVM test assertions: verified transaction propagation through
raw receipts and confirmed proper trace results via `debug_trace*`
methods (block, transaction, call).
- Reduced reliance on stale `EthRpc_WEB3` and clarified test references
from `val` to `node` for clarity and …
> test(eth-rpcapi): increase coverage of the rpcapi package using JSON-RPC calls

- CHANGELOG.md
- app/upgrades.go
- app/upgrades/types.go
- app/upgrades/v1_0_1/constants.go
- app/upgrades/v1_0_2/constants.go
- app/upgrades/v1_0_3/constants.go
- app/upgrades/v1_1_0/constants.go
- app/upgrades/v1_2_0/constants.go
- app/upgrades/v1_3_0/constants.go
- app/upgrades/v1_4_0/constants.go
- app/upgrades/v1_5_0/constants.go
- app/upgrades/v2_0_0/constants.go
- app/upgrades/v2_1_0/constants.go
- app/upgrades/v2_2_0/constants.go
- app/upgrades/v2_3_0/constants.go
- app/upgrades/v2_4_0/constants.go
- Prepares for https://github.com/NibiruChain/nibiru/issues/2313 by adding in the
other keepers to be available in upgrade handlers, similar to Osmosis and Archway.
- Replaces duplicate code on the majority of our upgrade handlers with a
reusable function.
> refactor(upgrades): add public keepers to upgrade handlers + DRY improvements

- CHANGELOG.md
- x/evm/keeper/grpc_query.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
> refactor: use the built-in max/min to simplify the code

- CHANGELOG.md
- app/app.go
- app/appconst/appconst.go
- app/server/evm_json_rpc.go
- app/server/evm_json_rpc_get.html
- app/server/start.go
- x/common/testutil/testnetwork/start_node.go
- Closes https://github.com/NibiruChain/nibiru/issues/1991
- **fix(appconst): runtime version noew shows git commit, binary version, etc.**
On all EVM RPC endpoints, a GET serves some text instead of an error. The page looks like this. It's lightweight and responsive with minimal CSS.
Run `just localnet` and then visit http://127.0.0.1:8545/
> feat(ux): add GET behavior to the Ethereum JSON-RPC endpoints for Nibiru so they return info instead of a blank page or error.

- token-registry/CHANGELOG.md
- token-registry/main/main.go
- token-registry/official_erc20s.json
- token-registry/official_tokens.go
- Fixes typos in Token Registry from #2317
- Improves robustness by referencing JSON files directly instead of using
separate variables for constants in the generation script
---
Refactored `ERC20S` and `BANK_COINS` into `LoadERC20s()` and `LoadBankCoins()` functions
that read from disk instead of relying on hardcoded variables. Updated `main.go` to load
tokens from `official_erc20s.json` and `official_bank_coins.json` prior to parsing and writing.
This prevents test runs from overwriting source-controlled files when executing the script,
resolving issues caused by `os.WriteFile` truncating the embedded JSON files on error.
> fix(token-registry): prevent overwriting embedded JSON files during tests

- CHANGELOG.md
- app/upgrades/v2_5_0/v2_5_0.go
- app/upgrades/v2_5_0/v2_5_0_test.go
- x/evm/evmtest/test_deps.go
- Attempt at fixing the consensus issue we saw on some nodes on our testnet-2 environment
This pull request modifies the `UpgradeStNibiContractOnMainnet` function in `v2_5_0.go` to improve the handling of the `StateDB` object by introducing a conditional check and cleanup mechanism.
Key changes:
* Replaced direct instantiation of `StateDB` with a conditional check to use `keepers.EvmKeeper.Bank.StateDB` if available. If not, it falls back to creating a new `StateDB` instance.
* Added a `defer` statement to reset `keepers.EvmKeeper.Bank.StateDB` to `nil` after its usage, ensuring proper cleanup and avoiding potential side effects.
> fix(evm): ensure stateDB doesn't persist after upgrade handler

- .gitignore
- CHANGELOG.md
- x/evm/codec.go
- x/evm/msg.go
This pull request introduces two new message types, `MsgCreateFunToken` and `MsgConvertCoinToEvm`, to the `x/evm` module. These changes extend the functionality of the module by registering and supporting these new message types.
* [`x/evm/codec.go`](diffhunk://#diff-52330b4824d2ae4d46412bc9b98dff8c2aa32877f2c663934c307f29288c591bR37-R38): Registered `MsgCreateFunToken` and `MsgConvertCoinToEvm` with the codec interface registry to enable their usage in transactions.
* [`x/evm/msg.go`](diffhunk://#diff-5ca9fbc3c4d517a8a59ba037f2a9fcda7b26c969c199a56a7701c9d850c650cdR37): Added `MsgConvertCoinToEvm` to the list of supported `sdk.Msg` types, ensuring compatibility with the `sdk.Msg` interface.
> feat(evm): add convert messages to codec | MsgCreateFunToken, MsgConvertCoinToEvm

- CHANGELOG.md
- app/simapp/state_test.go
- Closes #2349. This PR fixes a panic in simulation tests caused by an empty validator set during `InitChain`.
When the simulation framework generates zero accounts (`accs`), and/or when the number of initially bonded validators is set to zero (or exceeds the number of accounts), the staking module cannot initialize a validator set, causing the app to panic with:
```
validator set is empty after InitGenesis
```
```bash
make test-sim-nondeterminism
```
* Ensure at least 1 account is generated in `AppStateFn` if none were passed in.
* Clamp `numInitiallyBonded` to a minimum of 1 in `AppStateRandomizedFn`.
These changes guarantee that:
* The simulation has a non-empty account pool.
* The validator set always includes at least one bonded validator, avoiding invalid genesis states.
> fix(simapp): sim tests with empty validator set panic

- CHANGELOG.md
- eth/eip55.go
- eth/eip55_test.go
Added functionality to the Unmarshal method of EIP55Addr to accept ASCII hex strings (with and without 0x prefix) in addition to raw 20-byte addresses. This improves robustness for clients that may pass hex strings directly. Added corresponding unit tests to validate the new behavior.
> feat(eth): enhance EIP55Addr Unmarshal to support ASCII hex strings

- CHANGELOG.md
- cmd/nibid/cmd/base64.go
- x/evm/cli/cli_setup_test.go
- x/tokenfactory/cli/cli_test.go
- x/tokenfactory/cli/tx.go
This change implements CLI commands for:
- "nibiru.tokenfactory.v1.MsgSetDenomMetadata"
- "nibiru.tokenfactory.v1.MsgSudoSetDenomMetadata"
- Related https://github.com/NibiruChain/nibiru/pull/2242
These are used with `nibid build-stargate-wasm` to get base64-encoded transaction
messages that can be used with a CW3 multisig as a "Stargate" message. By
Stargate, we're referring to the `CosmosMsg::Stargate` variant that is now called
`CosmosMsg::Any`, as of `cosmwasm_std` v2.
```rust
pub enum CosmosMsg<T = Empty> {
// ...
#[deprecated = "Use `CosmosMsg::Any` instead (if you only target CosmWasm 2+ chains)"]
Stargate {
type_url: String,
value: Binary,
},
/// `CosmosMsg::Any` is the replaces the "stargate message" ΓÇô a message wrapped
/// in a [protobuf …
```
> feat(tokenfactory-cli): add CLI commands for set denom functions
